Harshada assignment 22
KrishnaKTechnocredits/Sep23JAVA pull request #160
Opened 2023-09-14 20:26 UTC by HarshadaJagtap11

2023-09-15 02:32 UTC, KrishnaKTechnocredits commented on src/harshada/MaxFrequency.java
> +		}System.out.println(input+" -> "+maxchar+" -> "+maxFreq);
Sop should be in the next line.

2023-09-15 02:34 UTC, KrishnaKTechnocredits requested changes
Please work on indentation and change code as requested.

2023-09-15 18:10 UTC, HarshadaJagtap11 commented on src/harshada/MaxFrequency.java
> +		}System.out.println(input+" -> "+maxchar+" -> "+maxFreq);
Code has been changed as requested

2023-09-15 18:11 UTC, HarshadaJagtap11 commented
> Please work on indentation and change code as requested.

Indentation has been corrected

2023-09-15 18:15 UTC, HarshadaJagtap11 commented
Output of Code 1:
![image](https://github.com/KrishnaKTechnocredits/Sep23JAVA/assets/112226610/07c3413a-6c1e-47d9-945d-198ec5b35bbb)
Output of Code 2:
![image](https://github.com/KrishnaKTechnocredits/Sep23JAVA/assets/112226610/f53a02e4-fabe-420e-8ae6-b346550dabdb)

2023-09-16 16:40 UTC, MargiVegada approved these changes
Code looks good to me

2023-09-16 17:40 UTC, merged